displayName: IPAPI Middleware
type: middleware

import: github.com/EAtrafego/traefik-ipapi-middleware

summary: "Middleware para Traefik que injeta cabeçalhos de geolocalização baseados em IP, utilizando a API ipapi.co."

testData:
  fields: country, city, ip            # Lista de campos a serem inseridos no header
  headerPrefix: X-IPAPI-               # Prefixo dos headers inseridos
  ipSource: RemoteAddr                 # Fonte do IP a ser analisado (RemoteAddr ou cabeçalho personalizado)
  apiURL: https://ipapi.co             # URL base da API utilizada
